import { serve } from "https://deno.land/std@0.168.0/http/server.ts";

const corsHeaders = {
  'Access-Control-Allow-Origin': '*',
  'Access-Control-Allow-Headers': 'authorization, x-client-info, apikey, content-type',
};

// Simple PDF generation using jsPDF-like approach
function generatePDF(domain: string, result: any): string {
  // In a real implementation, you would use a PDF library
  // For now, we'll create a simple text-based "PDF" (base64 encoded content)
  
  const content = `
WHOIS LOOKUP EVIDENCE REPORT
============================

Domain: ${result.domain_name}
Lookup Date: ${result.lookup_timestamp}

REGISTRANT INFORMATION
---------------------
Name: ${result.registrant_name}
Organization: ${result.registrant_org}

REGISTRATION DETAILS
-------------------
Registrar: ${result.registrar}
Registry: ${result.registry}
Creation Date: ${result.creation_date}
Expiry Date: ${result.expiry_date}

TECHNICAL DETAILS
----------------
Nameservers: ${result.nameservers}

DATA SOURCE
-----------
Source: ${result.data_source}

RISK ASSESSMENT
--------------
Risk Flag: ${result.risk_flag}

This document serves as evidence of the WHOIS lookup performed on ${result.lookup_timestamp}.
All information is provided as-is from the WHOIS database at the time of lookup.

--
Generated by Nova Dominium
For legal and compliance purposes only
`;

  // Convert to base64 (simulating PDF)
  return btoa(content);
}

serve(async (req) => {
  // Handle CORS preflight requests
  if (req.method === 'OPTIONS') {
    return new Response(null, { headers: corsHeaders });
  }

  try {
    const { domain, result } = await req.json();

    if (!domain || !result) {
      throw new Error("Invalid request: 'domain' and 'result' are required");
    }

    console.log(`Generating evidence PDF for: ${domain}`);

    const pdfBase64 = generatePDF(domain, result);

    return new Response(
      JSON.stringify({ pdf: pdfBase64 }),
      {
        headers: { ...corsHeaders, 'Content-Type': 'application/json' },
        status: 200,
      }
    );
  } catch (error) {
    console.error('Error in generate-evidence-pdf function:', error);
    const errorMessage = error instanceof Error ? error.message : 'An unknown error occurred';
    return new Response(
      JSON.stringify({ error: errorMessage }),
      {
        headers: { ...corsHeaders, 'Content-Type': 'application/json' },
        status: 400,
      }
    );
  }
});
